import "./globals.css";
import { Inter } from "next/font/google";
import AuthContextProvider from "../context/AuthContext";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Quoted",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <Navbar />
          <div className="flex flex-col min-h-[calc(100vh-4rem)] items-center justify-between p-6">
            {children}
          </div>
        </AuthContextProvider>
      </body>
    </html>
  );
}
